---
- name: Ensure Python MySQL library is installed
  ansible.builtin.apt:
    name: python3-pymysql
    state: present
  become: true

- name: Install MySQL server
  ansible.builtin.apt:
    name: mysql-server
    state: present
  become: true

- name: Ensure MySQL is running and enabled
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes
  become: true

- name: Configure MySQL root user
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: "*.*:ALL,GRANT"
    state: present
  become: true
