---
# roles/php/tasks/main.yml

- name: Install PHP {{ php_version }} and extensions for Joomla
  ansible.builtin.apt:
    name:
      - "php{{ php_version }}"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-zip"
      - "php{{ php_version }}-intl"
    state: present
    update_cache: yes

- name: Ensure php-fpm is running and enabled
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: started
    enabled: yes
